kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-pvc
  namespace: default
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi